### ISSUE TITLE
Missing import in `Abstract_ShinyAuth`

### ISSUE THREAD

**Issue by JapieVanTonder** [capiaas/ShinyAuth#1]
Hi @capiaas, 

Thanks for the great work!

I received the following error when using the package:
`Error in shinyApp(ui = self$ui(ui), server = self$server(server)) : 
could not find function "shinyApp"`

This ended up being due to a missing import for the `app` method of the `Abstract_ShinyAuth` R6 class.
`@importFrom shiny shinyApp` was missing in the documentation.

I forked the repo and added the missing import which now solves my problem. Do you want a PR for this?

**Comment by MyosQ** [comment]
Hi @JapieVanTonder and thanks for notifying us of this problem!
I fixed it now just like you did so no need for PR :)

Also, sorry for the late reply.

/Frej
